import 'package:flutter/material.dart';
import 'package:unicons/unicons.dart';

const List<IconData> cardIcons = <IconData>[
  UniconsLine.circle,
  UniconsLine.heart,
  UniconsLine.square,
  UniconsLine.star,
  UniconsLine.triangle,
  UniconsLine.atom,
  UniconsLine.brain,
  UniconsLine.dna,
  Icons.celebration,
  Icons.directions_car_filled,
  Icons.directions_bike,
  Icons.house,
  Icons.local_shipping,
  Icons.fastfood,
  Icons.album_sharp,
  Icons.forest,
  Icons.anchor,
  Icons.ac_unit,
  Icons.android,
  Icons.favorite,
  Icons.light,
  Icons.agriculture_sharp,
  Icons.airplanemode_on,
  Icons.umbrella,
  Icons.alarm,
  Icons.directions_subway_rounded,
  Icons.person,
  Icons.light_mode_outlined,
  Icons.bedtime_sharp,
  Icons.all_inclusive,
  Icons.wine_bar,
  Icons.star,
  Icons.headset_rounded,
  Icons.apple_sharp,
  Icons.whatshot_outlined,
  Icons.delete,
  Icons.audiotrack_rounded,
  Icons.back_hand_sharp,
  Icons.visibility,
  Icons.traffic_rounded,
  Icons.beach_access_rounded,
];
