// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAHk7DX9SjmRJo_iFekXKYYxR23kcmN3M',
    appId: '1:647339687851:web:70a357c12d268bfd551cee',
    messagingSenderId: '647339687851',
    projectId: 'kiddielearn-c19c1',
    authDomain: 'kiddielearn-c19c1.firebaseapp.com',
    storageBucket: 'kiddielearn-c19c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKgs8jk2ybRROh0EZhvyY-De1gwqF2u3c',
    appId: '1:647339687851:android:6b899a2a8f3988c8551cee',
    messagingSenderId: '647339687851',
    projectId: 'kiddielearn-c19c1',
    storageBucket: 'kiddielearn-c19c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArOnYgQ0vXtCa74cpYstXySD3nPNszyJo',
    appId: '1:647339687851:ios:ebd9f2f3bd2a4ac9551cee',
    messagingSenderId: '647339687851',
    projectId: 'kiddielearn-c19c1',
    storageBucket: 'kiddielearn-c19c1.appspot.com',
    iosBundleId: 'com.example.textspeech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArOnYgQ0vXtCa74cpYstXySD3nPNszyJo',
    appId: '1:647339687851:ios:ebd9f2f3bd2a4ac9551cee',
    messagingSenderId: '647339687851',
    projectId: 'kiddielearn-c19c1',
    storageBucket: 'kiddielearn-c19c1.appspot.com',
    iosBundleId: 'com.example.textspeech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAHk7DX9SjmRJo_iFekXKYYxR23kcmN3M',
    appId: '1:647339687851:web:cb4f037323c1012a551cee',
    messagingSenderId: '647339687851',
    projectId: 'kiddielearn-c19c1',
    authDomain: 'kiddielearn-c19c1.firebaseapp.com',
    storageBucket: 'kiddielearn-c19c1.appspot.com',
  );
}
